services:
  backend:
    build:
      context: ./ShareTunes/backend/
      dockerfile: Dockerfile
    volumes:
      - ./ShareTunes/backend:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"  # 内部ネットワークのみにポートを公開
    env_file:
      - ./ShareTunes/backend/.env
    restart: unless-stopped
    networks:
      - sharetunes-network

  frontend:
    build:
      context: ./ShareTunes/frontend/
      dockerfile: Dockerfile
    volumes:
      - ./ShareTunes/frontend:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"  # 内部ネットワークのみにポートを公開
    env_file:
      - ./ShareTunes/frontend/.env.local
    environment:
      - NEXT_PUBLIC_NODE_ENV=development  # 開発環境用の環境変数を設定
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sharetunes-network
      
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev  # HTTP専用の開発環境用Dockerfileを使用
    ports:
      - "80:80"  # HTTPのみポート公開
    volumes:
      - static_volume:/static
    depends_on:
      - backend
      - frontend
    networks:
      - sharetunes-network
    restart: unless-stopped

networks:
  sharetunes-network:
    driver: bridge

volumes:
  static_volume: