# Generated by Django 5.2 on 2025-04-16 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(help_text='LLMに送られたプロンプトテキスト')),
                ('llm_response', models.TextField(help_text='LLMからの生のレスポンス')),
                ('context_description', models.CharField(blank=True, help_text='推薦コンテキスト(気分、状況など)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '楽曲推薦',
                'verbose_name_plural': '楽曲推薦',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, help_text='この曲が推薦された理由の説明', null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='推薦リスト内での位置')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='recommendations.recommendation')),
            ],
            options={
                'verbose_name': '推薦楽曲',
                'verbose_name_plural': '推薦楽曲',
                'ordering': ['position'],
            },
        ),
    ]
