# Generated by Django 5.2 on 2025-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio_userprofile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='external_profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
